### ISSUE TITLE
Running parse on csv file with funky header causes PatternSyntaxException.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/parse#16]
Running parse on this file that processes the header field `Score Error (99.9%)` will cause parse to raise an exception.

```Caused by: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 154
(?<xBenchmarkx>[^,$]+)(?:,|$)(?<xModex>[^,$]+)(?:,|$)(?<xThreadsx>[^,$]+)(?:,|$)(?<xSamplesx>[^,$]+)(?:,|$)(?<xScorex>[^,$]+)(?:,|$)(?<xScorexErrorxx99xx9%xx>[^,$]+)(?:,|$)(?<xUnitx>[^,$]+)(?:,|$)
                                                                                                                                                          ^
	at java.util.regex.Pattern.error(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.groupname(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.group0(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.sequence(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.expr(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.<init>(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
	at io.hyperfoil.tools.parse.internal.RegexMatcher.<init>(RegexMatcher.java:61) ~[parse.jar:?]
	at io.hyperfoil.tools.parse.Exp.<init>(Exp.java:468) ~[parse.jar:?]
	at io.hyperfoil.tools.parse.factory.CsvFactory.lambda$headers$0(CsvFactory.java:36) ~[parse.jar:?]
	at io.hyperfoil.tools.parse.Exp.apply(Exp.java:962) ~[parse.jar:?]
	... 12 more
```

This is an example csv file

```
"Benchmark","Mode","Threads","Samples","Score","Score Error (99.9%)","Unit"
"foo","thrpt",1,15,3959.204321,99.361981,"ops/s"
"bar","thrpt",1,15,47278.187481,1523.003762,"ops/s"
"baz","thrpt",1,15,128.572278,2.898348,"ops/s"
```

This is the parse file

```
---
name: jmh
path: ".*?/(benchmark-)(?<suite>.*)(-output.csv)$"
nest: "suites.${{suite}}"
asText: CsvFactory
```

**Comment by willr3** [comment]
Thank you. There is now a test for this situation: https://github.com/Hyperfoil/parse/blob/master/src/test/java/io/hyperfoil/tools/parse/factory/CsvFactoryTest.java#L23
and the fix is in the next release cadec9b.

**Comment by whitingjr** [comment]
great thanks for fixing this.
